services:
- type: web
  name: groovy-rsvp
  env: python
  buildCommand: ""
  startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
  envVars:
    - key: EMAIL_ADDRESS
      sync: false
    - key: EMAIL_PASSWORD
      sync: false
    - key: ADMIN_EMAIL
      sync: false
